---
# Application parameters

# For the addresses of the pressure transducers, see the
# svi_PS_Sensor_Clasification_in.vi in dynalene_system LabVIEW project.
addresses_pressure_transducer_bus_0: [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 25]
addresses_pressure_transducer_bus_1: [1, 2]
addresses_pressure_transducer_bus_2: [3, 4]

# For the addresses of the flowmeters, see the
# svi_FS_Sensor_Clasification_In.vi in dynalene_system LabVIEW project.

# Chiller 1
addresses_flowmeter_bus_0: [1, 3, 6, 20]

# Chiller 2
addresses_flowmeter_bus_1: [2, 4, 7, 21]

# Exhaust air/ heat exchanger
addresses_flowmeter_bus_2: [22, 23, 24, 25]

# For the addresses of the power grid monitor, see the
# svi_PowerMonitorReadout.vi in dynalene_system LabVIEW project.
# Address 1: UPS monitor
# Address 2: raw chiller 1 monitor
# Address 3: raw chiller 2 monitor
addresses_power_grid_monitor: [1, 2, 3]

# For the addresses of the pier fans, see the app.vi in dynalene_system
# LabVIEW project.
#
# For pier fan 01, the running is decided by cabinet_control_and_status.K3.
# For pier fan 02, the running is decided by cabinet_control_and_status.K4.
# See svi_PFs_ModbusReadout.vi in the dynalene_system LabVIEW project.
addresses_pier_fan: [11, 12]

# For the addresses of the recirculation pumps, see the app.vi in
# dynalene_system LabVIEW project.
#
# For recirculation pump 01, the running is decided by
# cabinet_control_and_status.K1.
# For recirculation pump 02, the running is decided by
# cabinet_control_and_status.K2.
# See svi_RP_Readout_All.vi in the dynalene_system LabVIEW project.
addresses_recirculation_pump: [1, 2]

# For the addresses, ips and ports of the chillers, see the app.vi in
# dynalene_system LabVIEW project.

# For chiller 1, the running is decided by cabinet_control_and_status.K21.
# For chiller 2, the running is decided by cabinet_control_and_status.K22.
# See app.vi in the dynalene_system LabVIEW project.
addresses_chiller: [1, 1]
ips_chiller: ["192.168.90.1", "192.168.90.2"]
ports_chiller: [502, 502]

# The maximum values of the tank level sensor range. The unit is millimeters.
tank_level_sensor_max_range: [4300.0, 4300.0]

# The distances for the full level of the tank. The unit is millimeters.
tank_level_distance_full: [120.0, 120.0]

# The distances for the empty level of the tank. The unit is millimeters.
tank_level_distance_empty: [980.0, 980.0]
